name: backend-dev-devcontainer
services:
  dotnet-app:
    image: mcr.microsoft.com/devcontainers/dotnet:dev-10.0
    restart: unless-stopped
    command: sleep infinity
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT?error}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:8080}
      ConnectionStrings__PostgreSql: "Host=postgres-db;Port=5432;Database=${POSTGRES_DB?error};Username=${POSTGRES_USER?error};Password=${POSTGRES_PASSWORD?error}"
    volumes:
      - ../../:/workspaces/threads:cached
    depends_on:
      postgres-db:
        condition: service_healthy
    
    
  postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error}
      POSTGRES_DB: ${POSTGRES_DB?error}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  
  
volumes:
  postgres-data: